version: '0.1.0'
services:
  living-snow-testapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: living-snow-testapi
    ports:
      - "8080:80"
    volumes:
      - ./app:/app