name: fastapi-py39
channels:
  - conda-forge
dependencies:
  - anyio=3.6.1
  - black=22.6.0
  - bzip2=1.0.8
  - ca-certificates=2022.6.15
  - click=8.1.3
  - dataclasses=0.8
  - fastapi=0.79.0
  - flake8=5.0.4
  - freetype=2.10.4
  - giflib=5.2.1
  - h11=0.13.0
  - idna=3.3
  - importlib-metadata=4.11.4
  - jpeg=9e
  - lcms2=2.12
  - lerc=4.0.0
  - libcxx=14.0.6
  - libdeflate=1.12
  - libffi=3.4.2
  - libpng=1.6.37
  - libtiff=4.4.0
  - libwebp=1.2.3
  - libwebp-base=1.2.3
  - libxcb=1.13
  - libzlib=1.2.12
  - lz4-c=1.9.3
  - mccabe=0.7.0
  - mypy_extensions=0.4.3
  - ncurses=6.3
  - openjpeg=2.4.0
  - openssl=3.0.5
  - pathspec=0.9.0
  - pillow=9.2.0
  - pip=22.2.1
  - platformdirs=2.5.2
  - pthread-stubs=0.4
  - pycodestyle=2.9.1
  - pydantic=1.9.1
  - pyflakes=2.5.0
  - python=3.9.13
  - python_abi=3.9
  - readline=8.1.2
  - setuptools=63.3.0
  - sniffio=1.2.0
  - sqlite=3.39.2
  - starlette=0.19.1
  - tk=8.6.12
  - tomli=2.0.1
  - typed-ast=1.5.4
  - typing-extensions=4.3.0
  - typing_extensions=4.3.0
  - tzdata=2022a
  - uvicorn=0.18.2
  - wheel=0.37.1
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.5
  - zipp=3.8.1
  - zlib=1.2.12
  - zstd=1.5.2
  - pip:
    - six==1.16.0
